### ISSUE TITLE
ライセンスの表記について

### ISSUE THREAD

**Issue by inux39** [rev84/uhauha_programming#1]
MITライセンスとのことですが、MITライセンスによってライセンスの本文や著作権表示を記載する必要があるのではないでしょうか。
https://ja.osdn.net/projects/opensource/wiki/licenses%2FMIT_license

**Comment by rev84** [comment]
ご指摘ありがとうございます。
忘れておりました。
ライセンスに必要な文書等を追加しました。

**Comment by inux39** [comment]
確認いたしました。対応ありがとうございます。
